name: New Post
description: 새 블로그 글 작성을 위한 이슈 템플릿
title: "[Post] "
labels: ["post"]
body:
  - type: input
    id: title
    attributes:
      label: 글 제목
      description: 게시될 글의 제목
      placeholder: 예) "Transformer 기반 ML 모델 최적화"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: 작성자
      description: 작성자 닉네임
      placeholder: 예) Bob
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: 예정 발행일
      description: YYYY-MM-DD 형식
      placeholder: "2025-09-01"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: 글에 대한 간단한 소개 또는 목차
      placeholder: |
        "이 글에서는 Transformer 기반 머신러닝 모델의 구조와 추론 성능 최적화 기법을 다룹니다.

        목차:
        1. 모델 아키텍처 개요
        2. 경량화 전략
        3. 운영 환경에서의 실전 튜닝"
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트
      value: |
        - [ ] 초안 작성
        - [ ] 리뷰 요청
        - [ ] 최종 업로드
